// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * State represents the lifecycle state of a server connection.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * StateDisconnected is the zero value: no connection is established.
     */
    StateDisconnected = 0,

    /**
     * StateConnected means the channel is ready for operations.
     */
    StateConnected = 1,
};

/**
 * Type identifies the transport configured by a server profile.
 */
export enum Type {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeRCON = "rcon",
};
