// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EventResult identifies the randomly selected target of a world event.
 */
export class EventResult {
    "target": string;

    /** Creates a new EventResult instance. */
    constructor($$source: Partial<EventResult> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventResult instance from a string or object.
     */
    static createFrom($$source: any = {}): EventResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EventResult($$parsedSource as Partial<EventResult>);
    }
}
