// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails boundary for actions on the active server.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ReloadAllLua reloads all loaded Lua files on a Build 42 server.
 */
export function ReloadAllLua(): $CancellablePromise<void> {
    return $Call.ByID(1603316964);
}

/**
 * ReloadLua reloads a loaded Lua file matching the supplied path suffix.
 */
export function ReloadLua(file: string): $CancellablePromise<void> {
    return $Call.ByID(3883781911, file);
}

/**
 * ReloadOptions reloads server options from ServerOptions.ini.
 */
export function ReloadOptions(): $CancellablePromise<void> {
    return $Call.ByID(2204436627);
}

/**
 * SaveWorld saves the current world.
 */
export function SaveWorld(): $CancellablePromise<void> {
    return $Call.ByID(3370491437);
}

/**
 * SendMessage broadcasts a message to all connected players.
 */
export function SendMessage(message: string): $CancellablePromise<void> {
    return $Call.ByID(2127510311, message);
}

/**
 * StartRain starts rain. An intensity of zero lets the server choose it.
 */
export function StartRain(intensity: number): $CancellablePromise<void> {
    return $Call.ByID(2129536232, intensity);
}

/**
 * StartStorm starts a storm. A duration of zero lets the server choose it.
 */
export function StartStorm(duration: number): $CancellablePromise<void> {
    return $Call.ByID(3446166627, duration);
}

/**
 * StopRain stops rain on the server.
 */
export function StopRain(): $CancellablePromise<void> {
    return $Call.ByID(3501816584);
}

/**
 * StopServer saves the world and stops the server.
 */
export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(3227076877);
}

/**
 * StopWeather stops all weather on the server.
 */
export function StopWeather(): $CancellablePromise<void> {
    return $Call.ByID(640725850);
}

/**
 * TriggerGunshot creates a gunshot sound near a random player.
 */
export function TriggerGunshot(): $CancellablePromise<void> {
    return $Call.ByID(4142121520);
}

/**
 * TriggerHelicopter starts a helicopter event near a random player.
 */
export function TriggerHelicopter(): $CancellablePromise<void> {
    return $Call.ByID(1915518215);
}

/**
 * TriggerLightning strikes a randomly selected online player with lightning.
 */
export function TriggerLightning(): $CancellablePromise<$models.EventResult> {
    return $Call.ByID(902475888).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * TriggerThunder triggers thunder at a randomly selected online player.
 */
export function TriggerThunder(): $CancellablePromise<$models.EventResult> {
    return $Call.ByID(1369096040).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.EventResult.createFrom;
