// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ID identifies application functionality exposed to the user.
 */
export enum ID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Feature identifiers.
     */
    ConsoleExecuteCommand = "console.command.execute",
    ServerActionReloadAllLua = "serverAction.reloadAllLua",
    ServerActionReloadLua = "serverAction.reloadLua",
    ServerActionReloadOptions = "serverAction.reloadOptions",
    ServerActionSaveWorld = "serverAction.saveWorld",
    ServerActionSendMessage = "serverAction.sendMessage",
    ServerActionStartRain = "serverAction.startRain",
    ServerActionStartStorm = "serverAction.startStorm",
    ServerActionStopRain = "serverAction.stopRain",
    ServerActionStopServer = "serverAction.stopServer",
    ServerActionStopWeather = "serverAction.stopWeather",
    ServerActionTriggerGunshot = "serverAction.triggerGunshot",
    ServerActionTriggerHelicopter = "serverAction.triggerHelicopter",
    PlayerAddItems = "player.addItems",
    PlayerAddUser = "player.addUser",
    PlayerSpawnVehicle = "player.spawnVehicle",
    PlayerAddXP = "player.addXP",
    PlayerBan = "player.ban",
    PlayerUnban = "player.unban",
    PlayerCreateHorde = "player.createHorde",
    PlayerSetGodMode = "player.setGodMode",
    PlayerSetInvisible = "player.setInvisible",
    PlayerKick = "player.kick",
    PlayerTriggerLightning = "player.triggerLightning",
    PlayerTriggerThunder = "player.triggerThunder",
    PlayerSetNoClip = "player.setNoClip",
    PlayerList = "player.list",
    PlayerRemoveFromWhitelist = "player.removeFromWhitelist",
    PlayerSetAccessLevel = "player.setAccessLevel",
    PlayerSetPassword = "player.setPassword",
    PlayerTeleportToPlayer = "player.teleport.toPlayer",
    PlayerTeleportToCoordinates = "player.teleport.toCoordinates",
    PlayerSetVoiceBanned = "player.setVoiceBanned",
};
