[settings]
lockfile = true

[tools]
"go:github.com/google/go-licenses/v2" = "latest"
"go:github.com/wailsapp/wails/v3/cmd/wails3" = "v3.0.0-beta.24"
"pipx:reuse" = "latest"
go = "1.26"
node = "24"
pnpm = "latest"
task = "latest"
