// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FrontendError contains diagnostic context for an unexpected frontend error.
 */
export class FrontendError {
    "source": string;
    "name": string;
    "message": string;
    "stack": string;
    "componentStack": string;
    "route": string;

    /** Creates a new FrontendError instance. */
    constructor($$source: Partial<FrontendError> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("stack" in $$source)) {
            this["stack"] = "";
        }
        if (!("componentStack" in $$source)) {
            this["componentStack"] = "";
        }
        if (!("route" in $$source)) {
            this["route"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendError instance from a string or object.
     */
    static createFrom($$source: any = {}): FrontendError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FrontendError($$parsedSource as Partial<FrontendError>);
    }
}
