// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as player$0 from "../../../../beyenilmez/pz-admin/internal/player/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as session$0 from "../../../../beyenilmez/pz-admin/internal/session/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "player:updated": player$0.Update;
            "session:changed": session$0.Snapshot;
            "time": string;
        }
    }
}
