//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as player$0 from "../../../../beyenilmez/pz-admin/internal/player/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../../../../beyenilmez/pz-admin/internal/session/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "players:changed": $$createType0,
        "session:changed": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = player$0.Update.createFrom;
const $$createType1 = session$0.Snapshot.createFrom;

configure();
