// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ActionFailure identifies a player action that could not be completed.
 */
export class ActionFailure {
    "playerId": string;
    "message": string;

    /** Creates a new ActionFailure instance. */
    constructor($$source: Partial<ActionFailure> = {}) {
        if (!("playerId" in $$source)) {
            this["playerId"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionFailure instance from a string or object.
     */
    static createFrom($$source: any = {}): ActionFailure {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionFailure($$parsedSource as Partial<ActionFailure>);
    }
}

/**
 * ActionResult reports the outcome of a player action for each requested ID.
 */
export class ActionResult {
    "succeeded": string[];
    "failed": ActionFailure[];

    /** Creates a new ActionResult instance. */
    constructor($$source: Partial<ActionResult> = {}) {
        if (!("succeeded" in $$source)) {
            this["succeeded"] = [];
        }
        if (!("failed" in $$source)) {
            this["failed"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ActionResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("succeeded" in $$parsedSource) {
            $$parsedSource["succeeded"] = $$createField0_0($$parsedSource["succeeded"]);
        }
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField1_0($$parsedSource["failed"]);
        }
        return new ActionResult($$parsedSource as Partial<ActionResult>);
    }
}

/**
 * ItemGrant describes an item and quantity to give to a player.
 */
export class ItemGrant {
    "item": string;
    "count": number;

    /** Creates a new ItemGrant instance. */
    constructor($$source: Partial<ItemGrant> = {}) {
        if (!("item" in $$source)) {
            this["item"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemGrant instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemGrant {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemGrant($$parsedSource as Partial<ItemGrant>);
    }
}

/**
 * Player is a player known to the application.
 * Optional fields are nil when the active data source cannot observe them.
 */
export class Player {
    "id": string;
    "username": string;
    "accessLevel"?: string | null;
    "godMode"?: boolean | null;
    "invisible"?: boolean | null;
    "noClip"?: boolean | null;
    "banned"?: boolean | null;
    "voiceBanned"?: boolean | null;
    "whitelisted"?: boolean | null;
    "firstSeenAt": Date;
    "lastSeenOnlineAt": Date;
    "lastKnownOfflineAt": Date;

    /** Creates a new Player instance. */
    constructor($$source: Partial<Player> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("firstSeenAt" in $$source)) {
            this["firstSeenAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("lastSeenOnlineAt" in $$source)) {
            this["lastSeenOnlineAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("lastKnownOfflineAt" in $$source)) {
            this["lastKnownOfflineAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Player instance from a string or object.
     */
    static createFrom($$source: any = {}): Player {
        const $$createField9_0 = $Create.DateFromTime;
        const $$createField10_0 = $Create.DateFromTime;
        const $$createField11_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("firstSeenAt" in $$parsedSource) {
            $$parsedSource["firstSeenAt"] = $$createField9_0($$parsedSource["firstSeenAt"]);
        }
        if ("lastSeenOnlineAt" in $$parsedSource) {
            $$parsedSource["lastSeenOnlineAt"] = $$createField10_0($$parsedSource["lastSeenOnlineAt"]);
        }
        if ("lastKnownOfflineAt" in $$parsedSource) {
            $$parsedSource["lastKnownOfflineAt"] = $$createField11_0($$parsedSource["lastKnownOfflineAt"]);
        }
        return new Player($$parsedSource as Partial<Player>);
    }
}

/**
 * Update is emitted when the stored players for a server profile change.
 */
export class Update {
    "profileId": string;
    "players": Player[];

    /** Creates a new Update instance. */
    constructor($$source: Partial<Update> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("players" in $$source)) {
            this["players"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Update instance from a string or object.
     */
    static createFrom($$source: any = {}): Update {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("players" in $$parsedSource) {
            $$parsedSource["players"] = $$createField1_0($$parsedSource["players"]);
        }
        return new Update($$parsedSource as Partial<Update>);
    }
}

/**
 * XPGrant describes an amount of XP to give in one perk.
 */
export class XPGrant {
    "perk": string;
    "amount": number;

    /** Creates a new XPGrant instance. */
    constructor($$source: Partial<XPGrant> = {}) {
        if (!("perk" in $$source)) {
            this["perk"] = "";
        }
        if (!("amount" in $$source)) {
            this["amount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new XPGrant instance from a string or object.
     */
    static createFrom($$source: any = {}): XPGrant {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new XPGrant($$parsedSource as Partial<XPGrant>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ActionFailure.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Player.createFrom;
const $$createType4 = $Create.Array($$createType3);
