// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service exposes stored player data and owns the player store lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddItems gives each requested item to every player. A non-positive count
 * uses the server command's default count.
 */
export function AddItems(playerIDs: string[], items: $models.ItemGrant[]): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(660183175, playerIDs, items).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddLocalUser records a player in local history without changing the server.
 * All server-managed fields remain unknown until observed or changed by a
 * successful action.
 */
export function AddLocalUser(username: string): $CancellablePromise<void> {
    return $Call.ByID(1293327123, username);
}

/**
 * AddUser creates a new whitelisted server account and records its known
 * initial state. The password is sent to the server and is not persisted.
 */
export function AddUser(username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(84081850, username, password);
}

/**
 * AddVehicle spawns a vehicle next to each player.
 */
export function AddVehicle(playerIDs: string[], script: string): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(1901970135, playerIDs, script).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddXP gives each requested perk amount to every player.
 */
export function AddXP(playerIDs: string[], grants: $models.XPGrant[]): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(2089953901, playerIDs, grants).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Ban bans each player by username. Reason is optional; banIP also bans each
 * player's current IP address.
 */
export function Ban(playerIDs: string[], reason: string, banIP: boolean): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(998818691, playerIDs, reason, banIP).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateHorde spawns zombies near each player.
 */
export function CreateHorde(playerIDs: string[], count: number): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(793054328, playerIDs, count).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Kick disconnects each player from the server. Reason is optional.
 */
export function Kick(playerIDs: string[], reason: string): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(2695070056, playerIDs, reason).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Lightning triggers a lightning strike on each player.
 */
export function Lightning(playerIDs: string[]): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(1699893572, playerIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * List returns all known players for a server profile.
 */
export function List(profileID: string): $CancellablePromise<$models.Player[]> {
    return $Call.ByID(1377698586, profileID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RemoveFromWhitelist removes each player's account from the whitelist and
 * deletes successfully removed players from the local player history.
 */
export function RemoveFromWhitelist(playerIDs: string[]): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(2770138531, playerIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetAccessLevel changes the server access level of each player.
 */
export function SetAccessLevel(playerIDs: string[], level: string): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(2866151286, playerIDs, level).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetGodMode enables or disables god mode for each player.
 */
export function SetGodMode(playerIDs: string[], enabled: boolean): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(288807347, playerIDs, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetInvisible makes each player visible or invisible to zombies.
 */
export function SetInvisible(playerIDs: string[], enabled: boolean): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(499947397, playerIDs, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetNoClip enables or disables no-clip mode for each player.
 */
export function SetNoClip(playerIDs: string[], enabled: boolean): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(2237905755, playerIDs, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetPassword changes the password of each player's server account. Passwords
 * and the hashes returned by the server are never stored.
 */
export function SetPassword(playerIDs: string[], password: string): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(1591163019, playerIDs, password).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetVoiceBanned blocks or restores voice communication for each player.
 */
export function SetVoiceBanned(playerIDs: string[], banned: boolean): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(676477740, playerIDs, banned).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Teleport moves each player to the target player.
 */
export function Teleport(playerIDs: string[], targetPlayerID: string): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(3006027697, playerIDs, targetPlayerID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * TeleportToCoordinates moves each player to x,y,z coordinates.
 */
export function TeleportToCoordinates(playerIDs: string[], coordinates: string): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(1754900303, playerIDs, coordinates).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Thunder triggers thunder on each player.
 */
export function Thunder(playerIDs: string[]): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(1287356324, playerIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Unban removes each player's username ban.
 */
export function Unban(playerIDs: string[]): $CancellablePromise<$models.ActionResult> {
    return $Call.ByID(2741918398, playerIDs).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ActionResult.createFrom;
const $$createType1 = $models.Player.createFrom;
const $$createType2 = $Create.Array($$createType1);
