// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "../connection/models.js";

/**
 * Profile is a saved server connection.
 */
export class Profile {
    "id": string;
    "name": string;
    "connectionType": connection$0.Type;
    "host": string;
    "port": number;
    "version": string;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("connectionType" in $$source)) {
            this["connectionType"] = connection$0.Type.$zero;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile($$parsedSource as Partial<Profile>);
    }
}
