// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails v3 service for managing profiles and passwords.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete removes a profile, its password, and its associated player data.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3866365793, id);
}

/**
 * List returns all saved profiles.
 */
export function List(): $CancellablePromise<$models.Profile[]> {
    return $Call.ByID(122962354).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Save creates or updates a profile and stores a supplied password. An empty
 * password preserves the existing password when updating a profile.
 */
export function Save(p: $models.Profile, password: string): $CancellablePromise<$models.Profile> {
    return $Call.ByID(3664053219, p, password).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Profile.createFrom;
const $$createType1 = $Create.Array($$createType0);
