// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails v3 service for application configuration. It loads the
 * configuration at startup and persists every update atomically.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Config returns a copy of the current configuration.
 */
export function Config(): $CancellablePromise<$models.Config> {
    return $Call.ByID(1204379721).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetCheckUpdatesOnStartup controls the next launch's update check.
 */
export function SetCheckUpdatesOnStartup(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3306802779, enabled);
}

/**
 * SetLanguage validates and persists the selected application language.
 */
export function SetLanguage(language: string): $CancellablePromise<void> {
    return $Call.ByID(1508398047, language);
}

/**
 * SetTheme sets the theme to ThemeSystem, ThemeDark, or ThemeLight.
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(1836227950, theme);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
