const MAXIMUM_RCON_PACKET_BODY_BYTES = 4096;
const RCON_PACKET_BODY_OVERHEAD_BYTES = 10;

export const MAXIMUM_RCON_COMMAND_BYTES =
  MAXIMUM_RCON_PACKET_BODY_BYTES - RCON_PACKET_BODY_OVERHEAD_BYTES;
