// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpdateResult describes every outcome of a batch update. Command failures are
 * returned per option so one rejected value does not hide successful changes.
 */
export class UpdateResult {
    "updated": string[];
    "failed": { [_ in string]?: string };

    /** Creates a new UpdateResult instance. */
    constructor($$source: Partial<UpdateResult> = {}) {
        if (!("updated" in $$source)) {
            this["updated"] = [];
        }
        if (!("failed" in $$source)) {
            this["failed"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updated" in $$parsedSource) {
            $$parsedSource["updated"] = $$createField0_0($$parsedSource["updated"]);
        }
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField1_0($$parsedSource["failed"]);
        }
        return new UpdateResult($$parsedSource as Partial<UpdateResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
