// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails boundary for options on the active server.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns the current server option values.
 */
export function List(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(4127516251).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Update attempts every requested change and reports failures by option name.
 * Call List afterward to reconcile with the authoritative server state.
 */
export function Update(changes: { [_ in string]?: string }): $CancellablePromise<$models.UpdateResult> {
    return $Call.ByID(2343491282, changes).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.UpdateResult.createFrom;
