// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "../profile/models.js";

/**
 * Snapshot is the serializable public state of the active session.
 */
export class Snapshot {
    "profile": profile$0.Profile;
    "features": string[];
    "connected": boolean;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = (new profile$0.Profile());
        }
        if (!("features" in $$source)) {
            this["features"] = [];
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField0_0($$parsedSource["profile"]);
        }
        if ("features" in $$parsedSource) {
            $$parsedSource["features"] = $$createField1_0($$parsedSource["features"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

// Private type creation functions
const $$createType0 = profile$0.Profile.createFrom;
const $$createType1 = $Create.Array($Create.Any);
