// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails v3 boundary for the active server session.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "../profile/models.js";

/**
 * Connect looks up the profile and credentials, then opens its configured
 * channel. Connect holds the lock for the entire operation; the frontend shows
 * a spinner so no other methods are called concurrently.
 */
export function Connect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(1927976385, profileID);
}

/**
 * Disconnect closes the active channel. Idempotent.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(2905459187);
}

/**
 * Features returns the application features available through the active
 * connection. It returns an empty array while disconnected.
 */
export function Features(): $CancellablePromise<string[]> {
    return $Call.ByID(4186798162).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Profile returns the profile associated with the active connection.
 */
export function Profile(): $CancellablePromise<[profile$0.Profile, boolean]> {
    return $Call.ByID(677696214).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = profile$0.Profile.createFrom;
