// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry preserves the license text and attribution supplied by the report.
 */
export class Entry {
    "name": string;
    "identifier": string;
    "version"?: string;
    "source"?: string;
    "note"?: string;
    "text": string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("identifier" in $$source)) {
            this["identifier"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

export class Report {
    "applicationLicense": string;
    "entries": Entry[];

    /** Creates a new Report instance. */
    constructor($$source: Partial<Report> = {}) {
        if (!("applicationLicense" in $$source)) {
            this["applicationLicense"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     */
    static createFrom($$source: any = {}): Report {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new Report($$parsedSource as Partial<Report>);
    }
}

// Private type creation functions
const $$createType0 = Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
